#!/usr/bin/env python3
"""
Export trained ML models to C header files for Arduino/ESP32 deployment.

Generates:
  Code/AuraSync/iaq_model.h    -- IAQ MLP forward pass + weights
  Code/AuraSync/shower_model.h -- Shower CNN weights (PROGMEM) + predictShower()

Usage:
  cd project_root
  conda activate aursync-ml
  python Code/ml/export_models.py
"""
import math
import os
import joblib
import torch
import numpy as np

ROOT       = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MODELS_DIR = os.path.join(ROOT, "Data", "models")
OUT_DIR    = os.path.join(ROOT, "Code", "AuraSync")


# ── helpers ───────────────────────────────────────────────────────────────────

def fmt_float(v):
    """Format a float for C literal."""
    if math.isnan(v) or math.isinf(v):
        raise ValueError(f"Non-finite value: {v}")
    return f"{v:.8g}f"


def array1d(name, data, progmem=True):
    vals = ", ".join(fmt_float(float(x)) for x in data)
    pm = " PROGMEM" if progmem else ""
    return f"static const float{pm} {name}[{len(data)}] = {{{vals}}};\n"


def array2d(name, data, progmem=True):
    rows = len(data)
    cols = len(data[0])
    pm = " PROGMEM" if progmem else ""
    inner = ",\n  ".join(
        "{" + ", ".join(fmt_float(float(x)) for x in row) + "}"
        for row in data
    )
    return f"static const float{pm} {name}[{rows}][{cols}] = {{\n  {inner}\n}};\n"


def array3d(name, data, progmem=True):
    d0 = len(data)
    d1 = len(data[0])
    d2 = len(data[0][0])
    pm = " PROGMEM" if progmem else ""
    outer = []
    for plane in data:
        inner = ",\n    ".join(
            "{" + ", ".join(fmt_float(float(x)) for x in row) + "}"
            for row in plane
        )
        outer.append("  {\n    " + inner + "\n  }")
    body = ",\n".join(outer)
    return f"static const float{pm} {name}[{d0}][{d1}][{d2}] = {{\n{body}\n}};\n"


# ── IAQ MLP → iaq_model.h ────────────────────────────────────────────────────

def export_iaq(pkl_path: str, out_path: str):
    payload = joblib.load(pkl_path)
    pipe    = payload["model"]
    scaler  = pipe.named_steps["scaler"]
    mlp     = pipe.named_steps["clf"]

    assert hasattr(mlp, "coefs_"), "Expected MLPClassifier"
    # coefs_[i] shape: (n_in, n_out) — sklearn convention
    W0 = mlp.coefs_[0]   # (10, 64)
    b0 = mlp.intercepts_[0]  # (64,)
    W1 = mlp.coefs_[1]   # (64, 32)
    b1 = mlp.intercepts_[1]  # (32,)
    W2 = mlp.coefs_[2]   # (32, 3)
    b2 = mlp.intercepts_[2]  # (3,)

    mean  = scaler.mean_
    scale = scaler.scale_

    n_in  = W0.shape[0]   # 10
    h1    = W0.shape[1]   # 64
    h2    = W1.shape[1]   # 32
    n_out = W2.shape[1]   # 3

    lines = []
    lines.append("#pragma once\n")
    lines.append("// Auto-generated by export_models.py — DO NOT EDIT\n")
    lines.append("// IAQ MLP: StandardScaler + MLPClassifier(64, 32) -> 3 classes\n")
    lines.append("// Classes: 0=Good  1=Moderate  2=Poor\n\n")
    lines.append("#include <math.h>\n\n")

    lines.append(array1d("IAQ_SC_MEAN",  mean,  progmem=False))
    lines.append(array1d("IAQ_SC_SCALE", scale, progmem=False))
    lines.append("\n")

    # Store transposed: IAQ_W0[j][i] for cache-friendly row access in C
    lines.append(array2d("IAQ_W0", W0.T.tolist(),  progmem=False))  # [64][10]
    lines.append(array1d("IAQ_B0", b0.tolist(),    progmem=False))
    lines.append(array2d("IAQ_W1", W1.T.tolist(),  progmem=False))  # [32][64]
    lines.append(array1d("IAQ_B1", b1.tolist(),    progmem=False))
    lines.append(array2d("IAQ_W2", W2.T.tolist(),  progmem=False))  # [3][32]
    lines.append(array1d("IAQ_B2", b2.tolist(),    progmem=False))
    lines.append("\n")

    lines.append(f"""\
// Returns 0=Good, 1=Moderate, 2=Poor
static inline int predictIAQ(const float x[{n_in}]) {{
    // 1. StandardScaler
    float xs[{n_in}];
    for (int i = 0; i < {n_in}; i++)
        xs[i] = (x[i] - IAQ_SC_MEAN[i]) / IAQ_SC_SCALE[i];

    // 2. Hidden layer 1 ({n_in}->{h1}, ReLU)
    float h0[{h1}];
    for (int j = 0; j < {h1}; j++) {{
        float v = IAQ_B0[j];
        for (int i = 0; i < {n_in}; i++) v += IAQ_W0[j][i] * xs[i];
        h0[j] = v > 0.0f ? v : 0.0f;
    }}

    // 3. Hidden layer 2 ({h1}->{h2}, ReLU)
    float h1o[{h2}];
    for (int j = 0; j < {h2}; j++) {{
        float v = IAQ_B1[j];
        for (int k = 0; k < {h1}; k++) v += IAQ_W1[j][k] * h0[k];
        h1o[j] = v > 0.0f ? v : 0.0f;
    }}

    // 4. Output layer ({h2}->{n_out}), argmax
    int   best  = 0;
    float bestV = IAQ_B2[0];
    for (int k = 0; k < {h2}; k++) bestV += IAQ_W2[0][k] * h1o[k];
    for (int j = 1; j < {n_out}; j++) {{
        float v = IAQ_B2[j];
        for (int k = 0; k < {h2}; k++) v += IAQ_W2[j][k] * h1o[k];
        if (v > bestV) {{ bestV = v; best = j; }}
    }}
    return best;
}}
""")

    with open(out_path, "w") as f:
        f.writelines(lines)
    print(f"IAQ model  → {out_path}")


# ── Shower CNN → shower_model.h ───────────────────────────────────────────────

def adaptive_avg_pool_indices(in_size, out_size):
    """Return list of (start, end) index pairs matching PyTorch AdaptiveAvgPool1d."""
    bins = []
    for j in range(out_size):
        start = math.floor(j * in_size / out_size)
        end   = math.ceil((j + 1) * in_size / out_size)
        bins.append((start, end))
    return bins


def export_shower(pt_path: str, out_path: str):
    ckpt      = torch.load(pt_path, map_location="cpu")
    sd        = ckpt["state_dict"]
    threshold = float(ckpt["threshold"])
    n_feat    = int(ckpt.get("n_features", 6))
    win_size  = int(ckpt.get("window_size", 30))

    conv1_w = sd["conv1.weight"].numpy()   # [32, 6, 5]
    conv1_b = sd["conv1.bias"].numpy()     # [32]
    conv2_w = sd["conv2.weight"].numpy()   # [64, 32, 3]
    conv2_b = sd["conv2.bias"].numpy()     # [64]
    fc1_w   = sd["fc1.weight"].numpy()     # [32, 512]
    fc1_b   = sd["fc1.bias"].numpy()       # [32]
    fc2_w   = sd["fc2.weight"].numpy()     # [1, 32]
    fc2_b   = sd["fc2.bias"].numpy()       # [1]

    pool_out  = 8
    flat_size = conv2_w.shape[0] * pool_out   # 64 * 8 = 512
    pool_bins = adaptive_avg_pool_indices(win_size, pool_out)

    lines = []
    lines.append("#pragma once\n")
    lines.append("// Auto-generated by export_models.py — DO NOT EDIT\n")
    lines.append(f"// Shower 1D-CNN: Conv1d(6->32,k=5) -> Conv1d(32->64,k=3) -> AvgPool(8) -> FC(512->32) -> FC(32->1)\n")
    lines.append(f"// Threshold: {threshold:.4f}f\n\n")
    lines.append("#include <math.h>\n\n")
    lines.append(f"#define CNN_THRESHOLD {threshold:.4f}f\n")
    lines.append(f"#define CNN_N_FEAT    {n_feat}\n")
    lines.append(f"#define CNN_WIN       {win_size}\n\n")

    # Weights in PROGMEM
    lines.append(array3d("CNN_CONV1_W", conv1_w.tolist()))    # [32][6][5]
    lines.append(array1d("CNN_CONV1_B", conv1_b.tolist()))    # [32]
    lines.append(array3d("CNN_CONV2_W", conv2_w.tolist()))    # [64][32][3]
    lines.append(array1d("CNN_CONV2_B", conv2_b.tolist()))    # [64]
    lines.append(array2d("CNN_FC1_W",   fc1_w.tolist()))      # [32][512]
    lines.append(array1d("CNN_FC1_B",   fc1_b.tolist()))      # [32]
    lines.append(array2d("CNN_FC2_W",   fc2_w.tolist()))      # [1][32]
    lines.append(array1d("CNN_FC2_B",   fc2_b.tolist()))      # [1]
    lines.append("\n")

    # Pool bin constants
    pool_lines = ", ".join(f"{{{s},{e}}}" for s, e in pool_bins)
    lines.append(f"static const int CNN_POOL_BINS[{pool_out}][2] = {{{pool_lines}}};\n\n")

    lines.append(f"""\
// win[CNN_WIN][CNN_N_FEAT]: already StandardScaler-normalized (see feature_buffer.h)
// Returns sigmoid probability of shower event.
static float predictShower(const float win[CNN_WIN][CNN_N_FEAT]) {{
    // ── Conv1 [{n_feat}→32, k=5, pad=2] ─────────────────────────────────
    float c1[32][{win_size}];
    for (int oc = 0; oc < 32; oc++) {{
        for (int t = 0; t < {win_size}; t++) {{
            float v = CNN_CONV1_B[oc];
            for (int ic = 0; ic < {n_feat}; ic++) {{
                for (int k = 0; k < 5; k++) {{
                    int s = t - 2 + k;
                    if (s >= 0 && s < {win_size})
                        v += CNN_CONV1_W[oc][ic][k] * win[s][ic];
                }}
            }}
            c1[oc][t] = v > 0.0f ? v : 0.0f;  // ReLU
        }}
    }}

    // ── Conv2 [32→64, k=3, pad=1] ────────────────────────────────────────
    float c2[64][{win_size}];
    for (int oc = 0; oc < 64; oc++) {{
        for (int t = 0; t < {win_size}; t++) {{
            float v = CNN_CONV2_B[oc];
            for (int ic = 0; ic < 32; ic++) {{
                for (int k = 0; k < 3; k++) {{
                    int s = t - 1 + k;
                    if (s >= 0 && s < {win_size})
                        v += CNN_CONV2_W[oc][ic][k] * c1[ic][s];
                }}
            }}
            c2[oc][t] = v > 0.0f ? v : 0.0f;  // ReLU
        }}
    }}

    // ── AdaptiveAvgPool1d(8) ──────────────────────────────────────────────
    float pool[64][{pool_out}];
    for (int ch = 0; ch < 64; ch++) {{
        for (int j = 0; j < {pool_out}; j++) {{
            int s = CNN_POOL_BINS[j][0], e = CNN_POOL_BINS[j][1];
            float sum = 0.0f;
            for (int t = s; t < e; t++) sum += c2[ch][t];
            pool[ch][j] = sum / (float)(e - s);
        }}
    }}

    // ── Flatten [64×8 → {flat_size}] ──────────────────────────────────────
    float flat[{flat_size}];
    for (int ch = 0; ch < 64; ch++)
        for (int j = 0; j < {pool_out}; j++)
            flat[ch * {pool_out} + j] = pool[ch][j];

    // ── FC1 [{flat_size}→32, ReLU] ────────────────────────────────────────
    float h[32];
    for (int j = 0; j < 32; j++) {{
        float v = CNN_FC1_B[j];
        for (int k = 0; k < {flat_size}; k++) v += CNN_FC1_W[j][k] * flat[k];
        h[j] = v > 0.0f ? v : 0.0f;
    }}

    // ── FC2 [32→1, sigmoid] ────────────────────────────────────────────────
    float logit = CNN_FC2_B[0];
    for (int k = 0; k < 32; k++) logit += CNN_FC2_W[0][k] * h[k];
    return 1.0f / (1.0f + expf(-logit));
}}
""")

    with open(out_path, "w") as f:
        f.writelines(lines)
    print(f"Shower CNN → {out_path}")


# ── main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)

    export_iaq(
        os.path.join(MODELS_DIR, "iaq_rf_v1.pkl"),
        os.path.join(OUT_DIR, "iaq_model.h"),
    )
    export_shower(
        os.path.join(MODELS_DIR, "shower_cnn_v1.pt"),
        os.path.join(OUT_DIR, "shower_model.h"),
    )
    print("Done.")
