[platformio]
build_dir = C:/.pio_build/VOCLogger

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

lib_deps =
    https://github.com/BoschSensortec/Bosch-BSEC2-Library.git
    https://github.com/BoschSensortec/Bosch-BME68x-Library.git
    https://github.com/mobizt/Firebase-ESP-Client

; BSEC2 ships precompiled .a files — this flag prevents linker symbol conflicts
build_flags =
    -Wl,--allow-multiple-definition

monitor_speed = 115200
